[package]
name = "cycle_stark"
version = "0.1.0"
authors = ["Dalmas Ogembo<dalmas.ogembo@livesoftwaredeveloper.com>"]

[[target.starknet-contract]]
sierra = true
casm = true

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html
[dependencies]
starknet = "2.6.4"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.26.0" }

# current devnet rs seed 3446092628

# [[tool.snforge.fork]]
# name = "GoerliFork"
# url = "https://starknet-goerli.infura.io/v3/958e1b411a40480eacb8c0f5d640a8ec"
# block_id.tag = "Latest"

# [tool.sncast.account1]
# account = "account1"
# accounts-file = "/home/dalmas/.starknet_accounts/starknet_open_zeppelin_accounts.json"
# url = "http://localhost:5050/rpc"


# [tool.sncast.account2]
# account = "account2"
# accounts-file = "/home/dalmas/.starknet_accounts/starknet_open_zeppelin_accounts.json"
# url = "http://localhost:5050/rpc"

# [tool.sncast.argent_account]
# account = "argent_account"
# accounts-file = "/home/dalmas/.starknet_accounts/starknet_open_zeppelin_accounts.json"
# url = "https://starknet-goerli.infura.io/v3/958e1b411a40480eacb8c0f5d640a8ec"

# [tool.sncast.new_account]
# account = "new_account"
# accounts-file = "/home/dalmas/.starknet_accounts/starknet_open_zeppelin_accounts.json"
# url = "http://localhost:5050/rpc"

# [tool.sncast.argent_account1]
# account = "argent_account1"
# accounts-file = "/home/dalmas/.starknet_accounts/starknet_open_zeppelin_accounts.json"
# url = "https://starknet-goerli.infura.io/v3/958e1b411a40480eacb8c0f5d640a8ec"
