import { Contract, Account, Provider } from 'starknet'
import { connect, disconnect } from 'starknetkit'
// Create a file called abi.json in  your assets folder under src and paste the sierra.json file generated by scarb build that you declared earlier.
import { abi } from '../assets/abi.json'

const PRIVATE_KEY = "0x819033027885bc1840b6d564b6e8f68c" // Pick an account and pass its private key here
const ACCOUNT_ADDRESS = "0x77a6390ab3dc3045df373b93bf8b93899c3ad5111da9b66c54b62ddc98e7d4" // Account address of the selected account from starknet-devnet

/* The contract address below is modified, also modify yours and remove any zeros after x ie
if your contract address is 0x004236... or 0x04236... - remove the two/one zero(s) after x to be
0x4236...
*/

const CONTRACT_ADDRESS = "0x21bfe736c3e830f6b606aaba5f16fbda2a782a67fbeaaf97cb2786426af2870" // Contract address

const provider = new Provider({ rpc: { nodeUrl: "http://localhost:5050/rpc" } })
const account = new Account(provider, ACCOUNT_ADDRESS, PRIVATE_KEY)
const contract = new Contract(abi, CONTRACT_ADDRESS, account)


async function connectWallet() {
    return await connect({ webWalletUrl: "https://web.argent.xyz" })
}

async function disconnectWallet() {
    await disconnect()
}

export { ACCOUNT_ADDRESS, CONTRACT_ADDRESS, provider, account, contract, disconnectWallet }
export default connectWallet 