import { Contract, Account, Provider } from 'starknet'
import { connect, disconnect } from 'starknetkit'
// Create a file called abi.json in  your assets folder under src and paste the sierra.json file generated by scarb build that you declared earlier.
import { abi } from '../assets/abi.json'

const PRIVATE_KEY = "0x865c9c050b1e0f4cb2b7c12305b374c" // Pick an account and pass its private key here
const ACCOUNT_ADDRESS = "0x2be9b4b8680ec18c743bdc596cb1b27dfe87a678a2735b0ea863dd2e549f948" // Account address of the selected account from starknet-devnet

/* The contract address below is modified, also modify yours and remove any zeros after x ie
if your contract address is 0x004236... or 0x04236... - remove the two/one zero(s) after x to be
0x4236...
*/

const CONTRACT_ADDRESS = "0x2885a759784b5f88caa03a3e586ad1ad4d0abd7c3521f53f917ef0dbed30e20" // Contract address

const provider = new Provider({ rpc: { nodeUrl: "http://localhost:5050/rpc" } })
const account = new Account(provider, ACCOUNT_ADDRESS, PRIVATE_KEY)
const contract = new Contract(abi, CONTRACT_ADDRESS, account)


async function connectWallet() {
    return await connect({ webWalletUrl: "https://web.argent.xyz" })
}

async function disconnectWallet() {
    await disconnect()
}

export { ACCOUNT_ADDRESS, CONTRACT_ADDRESS, provider, account, contract, disconnectWallet }
export default connectWallet 